### ISSUE TITLE
Event/view past event button: show the past events

### ISSUE THREAD

**Issue by pratiksj** [hamrolifebank/event-pwa#67]
## Todo

- [x] #76
- [x] #77
- [x] #78

**Comment by SurazGaire** [comment]
Todo :
- [ ] UI landing page for the past events
- [ ] BL sort data on the basis of event data 
- [ ] Data GET all the event list from registery server
